services:
  backend:
    image: samurcorrea/rentaride2-backend:latest
    container_name: rentaride2back2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/rentaride2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 620759082
      SPRING_PROFILES_ACTIVE: docker
      UPLOAD_DIR: file:/app/uploads/
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads  
      - backend_uploads:/app/uploads  
    networks:
      - app-network

  frontend:
    image: samurcorrea/rentaride2-frontend:latest
    container_name: rentaride2front2
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      BACKEND_API_URL: http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_uploads:
