services:
  backend:
    image: samurcorrea/rentaride-backend-localhost:latest
    container_name: rentaride2back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/rentaride2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 620759082
      SPRING_PROFILES_ACTIVE: docker
      UPLOAD_DIR: /app/uploads/
       # Configuración para recursos estáticos
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: file:/app/uploads/
      SPRING_MVC_STATIC_PATH_PATTERN: /uploads/**
    ports:
      - "8080:8080"

    networks:
      - app-network

  frontend:
    image: samurcorrea/rentaride-frontend-localhost:latest
    container_name: rentaride2front
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      BACKEND_API_URL: http://localhost:8080
    volumes:
      - ./uploads:/usr/share/nginx/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
